# Assignment 7


### 1. What is NumPy and what are its main advantages over regular Python lists?
NumPy (Numerical Python) is a powerful library for numerical computations in Python. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

**Advantages over regular Python lists:**
- Faster performance using optimized C code under the hood
- Requires less memory
- Supports vectorized operations
- Convenient for matrix and linear algebra operations

In [1]:
import numpy as np

# Coding Challenge
arr = np.array([1, 2, 3, 4])
print("Original Array:", arr)
print("Addition:", arr + 2)
print("Multiplication:", arr * 3)

Original Array: [1 2 3 4]
Addition: [3 4 5 6]
Multiplication: [ 3  6  9 12]


### 2. Creating different types of arrays

In [2]:
# Zeros, Ones, Random Integers
zeros = np.zeros((3, 3))
ones = np.ones((3, 3))
randoms = np.random.randint(1, 11, size=(3, 3))
print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Random Integers:\n", randoms)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random Integers:
 [[4 4 7]
 [1 8 9]
 [9 1 7]]


### 3. Indexing and Slicing in NumPy

In [3]:
# 2D slicing
array2d = np.arange(16).reshape(4, 4)
print("Original 4x4 Array:\n", array2d)
subarray = array2d[1:3, 1:3]
print("2x2 Subarray:\n", subarray)

Original 4x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2x2 Subarray:
 [[ 5  6]
 [ 9 10]]


### 4. Statistical Functions: Mean, Median, Std Dev

In [4]:
data = np.random.rand(100)
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))

Mean: 0.4446438146416248
Median: 0.42167635551961646
Standard Deviation: 0.2968791733125041


### 5. Element-wise and Matrix Operations

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Element-wise Addition:\n", A + B)
print("Element-wise Subtraction:\n", A - B)
print("Matrix Multiplication:\n", np.dot(A, B))

Element-wise Addition:
 [[ 6  8]
 [10 12]]
Element-wise Subtraction:
 [[-4 -4]
 [-4 -4]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


### 6. Broadcasting in NumPy

In [6]:
matrix = np.ones((3, 3))
vector = np.array([1, 2, 3])
print("Matrix + Vector:\n", matrix + vector)  # Broadcasting

Matrix + Vector:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


### 7. Handling NaN values in NumPy

In [7]:
arr_with_nan = np.array([1, 2, np.nan, 4, np.nan, 6])
mean_val = np.nanmean(arr_with_nan)
arr_filled = np.where(np.isnan(arr_with_nan), mean_val, arr_with_nan)
print("Array with NaNs replaced by mean:", arr_filled)

Array with NaNs replaced by mean: [1.   2.   3.25 4.   3.25 6.  ]


### 8. reshape() and flatten() methods

In [8]:
arr1d = np.arange(12)
reshaped = arr1d.reshape((3, 4))
flattened = reshaped.flatten()
print("Reshaped 3x4:\n", reshaped)
print("Flattened back to 1D:", flattened)

Reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened back to 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]


### 9. numpy.linalg for linear algebra

In [9]:
from numpy.linalg import inv, eig

matrix = np.array([[4, 2], [1, 3]])
inverse = inv(matrix)
eigen_vals, eigen_vecs = eig(matrix)

print("Inverse:\n", inverse)
print("Eigenvalues:", eigen_vals)
print("Eigenvectors:\n", eigen_vecs)

Inverse:
 [[ 0.3 -0.2]
 [-0.1  0.4]]
Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### 10. Saving and Loading NumPy arrays

In [10]:
# Save and Load
arr_to_save = np.array([10, 20, 30])
np.save("saved_array.npy", arr_to_save)
loaded_array = np.load("saved_array.npy")
print("Loaded Array:", loaded_array)

Loaded Array: [10 20 30]
